### ISSUE TITLE
Server and database - fail to upload map

### ISSUE THREAD

**Issue by Justinas256** [Justinas256/JobFairUCLL#5]
Uploading map(image) works correctly while running web application locally and using postgresql. On server it does not work. Probably because on server we are using derby database, not postgresql.

**Comment by gretagreat** [comment]
Database was changed from derby to postgresql. 
PosgreSQL database credentials:
        url: 104.196.35.213:5432/jobFair
        user: postgres
        password: jobfair

Uploading map(image) works locally and on the server.
